stages:
  - build
  - bootup-staging
  - deploy-staging
  - after-staging
  - deploy-prod

.kubectl:
  image:
    name: registry.git.rwth-aachen.de/zoomoid/docker-kubectl:1.19.3
    entrypoint: ['/docker-entrypoint.sh']
  before_script:
    - kubectl config use-context runner/web
  tags:
    - kubernetes

.build:
  image: gcr.io/kaniko-project/executor:debug
  stage: build
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  tags: 
    - kubernetes

variables:
  NAMESPACE: "-n web"
  SERVICE: 'staging-zoomoid-de'
  HOSTS: '["staging.zoomo.id","staging.zoomoid.de"]'

build-staging:
  except:
    - master
  extends: .build
  script: 
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --target zoomoid-de --destination $CI_REGISTRY_IMAGE/dev:$CI_COMMIT_SHORT_SHA

build-prod:
  only:
  - master
  - merge_requests
  - tags
  extends: .build
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --target zoomoid-de --destination $CI_REGISTRY_IMAGE/stable:latest
  tags: 
    - kubernetes

bootup-staging:
  except:
    - master
  stage: bootup-staging
  extends: .kubectl
  script:
    - cat $BOOTUP_STAGING | tee ingress.json
    - kubectl apply -f ingress.json

deploy-staging:
  except:
    - master
  stage: deploy-staging
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomoid.de
  script:
    - kubectl rollout restart deployment/zoomoid-de

takedown-staging:
  except:
    - master
  stage: after-staging
  when: manual
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomoid.de
  script:
    - cat $TAKEDOWN_STAGING | tee ingress.json
    - kubectl apply -f ingress.json

auto-takedown-staging:
  only:
    - master
  stage: deploy-prod
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomoid.de
  script:
    - cat $TAKEDOWN_STAGING | tee ingress.json
    - kubectl apply -f ingress.json

deploy-production:
  only:
    - master
  stage: deploy-prod
  extends: .kubectl
  script: 
    - kubectl rollout restart deployment/zoomoid-de
  environment:
    name: production
    url: https://zoomoid.de