stages:
  - build
  - bootup-staging
  - deploy-staging
  - after-staging
  - deploy-prod

.kubectl:
  image:
    name: registry.git.rwth-aachen.de/zoomoid/docker-kubectl:latest
    entrypoint: ['/docker-entrypoint.sh']
  before_script:
    - echo $kube_config | base64 -d > runner.conf
    - export KUBECONFIG="$KUBECONFIG:$(pwd)/runner.conf"
    - kubectl config use-context runner@kubernetes
  tags:
    - kubernetes

variables:
  NAMESPACE: "-n web"
  SERVICE: 'staging-zoomoid-de'
  HOSTS: '["staging.zoomo.id","staging.zoomoid.de"]'

build-staging:
  except:
    - master
  image: docker:latest
  stage: build
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/nightly:latest
    - docker push $CI_REGISTRY_IMAGE/nightly:latest
  tags: 
    - kubernetes

build-prod:
  image: docker:latest
  stage: build
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE/stable .
    - docker push $CI_REGISTRY_IMAGE/stable:latest
  tags: 
    - kubernetes

bootup-staging:
  except:
    - master
  stage: bootup-staging
  extends: .kubectl
  script:
    - cat $BOOTUP_STAGING | tee ingress.json
    - kubectl apply -f ingress.json

deploy-staging:
  except:
    - master
  stage: deploy-staging
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomo.id
  script:
    - kubectl set image deployment/$SERVICE $SERVICE=$CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA
    - kubectl rollout status deployment/$SERVICE

takedown-staging:
  except:
    - master
  stage: after-staging
  when: manual
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomo.id
  script:
    - cat $TAKEDOWN_STAGING | tee ingress.json
    - kubectl apply -f ingress.json

auto-takedown-staging:
  only:
    - master
  stage: deploy-prod
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomo.id
  script:
    - cat $TAKEDOWN_STAGING | tee ingress.json
    - kubectl apply -f ingress.json

deploy-production:
  only:
    - master
  stage: deploy-prod
  extends: .kubectl
  script: 
    - kubectl rollout restart deployment/zoomoid-de
  environment:
    name: production
    url: https://zoomo.id