stages:
  - build-staging
  - create-patches
  - bootup-staging
  - deploy-staging
  - takedown-staging
  - build-prod
  - deploy-prod

.kubectl:
  image:
    name: registry.git.rwth-aachen.de/zoomoid/docker-kubectl:latest
    entrypoint: ['./docker-entrypoint.sh']
  before_script:
    - cat /bin/k
  tags:
    - kube

variables:
  NAMESPACE: "-n web"

build-staging:
  image: docker:latest
  stage: build-staging
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA
  tags: 
    - occloxium-docker

build-prod:
  image: docker:latest
  stage: build-prod
  when: manual
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE/stable .
    - docker push $CI_REGISTRY_IMAGE/stable:latest
  tags: 
    - occloxium-docker

create-patches:
  stage: build-staging
  extends: .kubectl
  variables:
    SERVICE: 'staging-zoomoid-de'
    HOSTS: '["staging.zoomo.id","staging.zoomoid.de"]'
  script:
    - python3 /create-patches.sh --service $SERVICE --hosts $HOSTS
    - cp /**.patch.json ./
    - pwd
    - ls .
  artifacts:
    paths:
      - ./remove-staging.patch.json
      - ./add-staging.patch.json

bootup-staging:
  stage: bootup-staging
  extends: .kubectl
  script:
    - k patch ingress --patch "$(cat ./add-staging.patch.json)"

deploy-staging:
  stage: deploy-staging
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomo.id
  script:
    - k set image deployment/staging-zoomoid-de staging-zoomoid-de=$CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_SHORT_SHA
    - k rollout status deployment/staging-zoomoid-de

takedown-staging:
  stage: takedown-staging
  extends: .kubectl
  environment:
    name: staging
    url: https://staging.zoomo.id
  script:
    - k patch ingress --patch "$(cat ./remove-staging.patch.json)"

deploy-production:
  stage: deploy-prod
  extends: .kubectl
  when: manual  
  script: 
    - k rollout restart deployment/zoomoid-de
  environment:
    name: production
    url: https://zoomo.id