import React from "react";
import Head from "next/head";
import Image from "next/image";
import Section from "../components/Section";
import Footer from "../components/Footer";
import useSwr from "swr";
import Navigation from "components/navigation/Navigation";

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const { data, error } = useSwr("/api/releases", fetcher);
  if (error) {
    return (<></>)
  }
  if (!data) {
    return (<></>)
  }

  const releases = data.releases;
  const releasesSections = releases.map((release) => (
    <Section key={release.title} release={release}></Section>
  ));

  return (
    <div>
      <Head>
        <title>zoomoid.de</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navigation></Navigation>
      <main className="text-white">
        <section className="flex justify-end py-[6.6vmax] lg:py-[1.6vmax] px-[4vw] xl:max-w-[1800px] mx-auto">
          <div className="lg:w-[75%] px-4 md:px-0 relative">
            <div className="relative mb-8">
              <Image
                layout="responsive"
                src="/img/banner.jpg"
                alt="Zoomoid at a busstop gazing into the night"
                width={2500}
                height={1095}
              ></Image>
            </div>
            <h1 className="text-5xl sm:text-5xl md:text-7xl lg:text-7xl xl:text-7xl font-semibold  font-sans">
              Zoomoid is a young, aspiring artist and producer, based in Aachen,
              Germany. He&apos;s making electronic music with a concept and a
              heartbeat.
            </h1>
          </div>
        </section>
        <section className="py-[6.6vmax] px-[4vw] xl:max-w-[1800px] mx-auto">
          <article id="about" className="flex justify-end mb-24">
            <div className="lg:w-[75%]">
              <div className="md:grid grid-cols-12 px-4 md:px-0">
                <div className="col-span-2">
                  <div className="md:px-4 pb-4">
                    <hr className="my-2 border-t-2 md:border-t" />
                  </div>
                </div>
                <div className="col-span-1"></div>
                <div className="col-span-2 my-4 md:my-0">
                  <p className="text-2xl md:text-normal font-sans md:font-serif">
                    Intro
                  </p>
                </div>
                <div className="col-span-7 text-xl sm:text-2xl leading-normal">
                  <p className="">
                    I&apos;ve been tinkering around with electronic music for
                    almost a decade now. My experiments with different styles
                    lead to the genres I like today and such have in turn
                    inspired new creations. Over the past years, I&apos;ve
                    learned that I want my music to be organic and harmonic, and
                    that my instrument of choice is a synthesizer.
                  </p>
                </div>
              </div>
            </div>
          </article>
          <article id="work" className="flex justify-end">
            <div className="lg:w-[75%]">
              <div className="md:grid grid-cols-12 px-4 md:px-0">
                <div className="col-span-2">
                  <div className="md:px-4 text-lg md:text-normal">
                    2018-2021
                  </div>
                </div>
                <div className="col-span-1"></div>
                <div className="col-span-2 my-4 md:my-0">
                  <p className="text-2xl md:text-normal font-sans md:font-serif">
                    Work
                  </p>
                </div>
                <div className="col-span-7 text-xl sm:text-2xl leading-normal">
                  <p className="mb-4">
                    The first large release of Zoomoid landed in September 2018,
                    with more quickly succeeding the album “Life Is About Making
                    Memories”.
                  </p>
                  <p className="mb-4">
                    In 2019, Zoomoid released his concept album “Eigenräume”,
                    which, up to this day, is one of his proudest releases. The
                    album was followed by a strong style change with “Public
                    Transportation”, which some swear, was his best work yet. In
                    December 2019, Zoomoid released “301 Permanently Moving”, a
                    nerdy joke about HTTP, which introduced harder techno beats
                    and a remix of one of his favourite tracks from
                    “Eigenräume”, “Outer Space”.
                  </p>
                  <p className="mb-4">
                    The year 2020 saw Zoomoid releasing the “Shades of Yellow”
                    EP in May, while the pandemic had most of us stuck at home.
                    “Shades of Yellow” began to introduce more emotions into his
                    music. Some say that this was the time, his talent to tell a
                    story with his music came present. Later that year, he
                    released “Voyager”, a tribute to his love for space and
                    mankind&apos;s venture into the unknown. The 10-track album
                    tells a story of leaving earth and the tracks unfold into a
                    mixture of driving Techno and beautifully crafted melodies
                    and harmonies.
                  </p>
                  <p className="mb-4">
                    2021 was his quietest year yet, only having released the
                    super-emotional “Sehnsucht” EP, with sounds so soft and
                    intimate that they hardly fit his previous profile.
                    Nevertheless, “Sehnsucht” incorporates some classic Zoomoid
                    elements such as recorded atmospheres from some of his
                    favorite places and, once more, a remix version of one of
                    his previous songs that is very dear to him, “Malheureux en
                    Amour”.
                  </p>
                </div>
              </div>
            </div>
          </article>
        </section>
        <section>{releasesSections}</section>
      </main>
      <Footer></Footer>
    </div>
  );
}
